<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icone.ico</ApplicationIcon>
    <AssemblyName>MCD2CustomSkin</AssemblyName>
    <Product>MCD2 Custom Skin</Product>
    <Title>MCD2 Custom Skin</Title>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icone.png" />
    <Resource Include="icone.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="heroes_catalog.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="oo2core_9_win64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

</Project>
